name: defafio-fullcycle-nginx

services:
  app:
    build: app
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/usr/src/app
    networks:
      - fullcycle

  nginx:
    image: nginx:1.27.0
    container_name: nginx
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fullcycle

  db:
    image: mysql:5.7.16
    container_name: db
    command: --innodb-use-native-aio=0 --init-file /data/application/init.sql
    restart: always
    tty: true
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: T2245RFHG_9jfd
      MYSQL_DATABASE: nodedb
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=T2245RFHG_9jfd
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      - fullcycle

networks:
  fullcycle: